import Head from "next/head";
import Image from "next/image";
import Banner from "../components/Admission/Banner";
import Navbar from "../components/Navbar/Navbar";
import ScrollView from "../components/ScrollView";
import styles from "../styles/Home.module.css";

export default function Admission() {
  return (
    <>
      <Head>
        <title>College King</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      <div className={styles.container}>
        <Banner />
        <p className="mt-4 text-sm ml-2">
          Home {">"} College {">"} MBA {">"} IIMA {">"} Admissions
        </p>
        <ScrollView />
      </div>
    </>
  );
}
